POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Chakib",
  "name": "Chakib Shkippa",
  "password": "alphabet"
}
###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "alphabet"
}