POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Chakib2",
  "name": "Chakib Shkippa",
  "password": "Sala1ne!"
}
###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "wfq",
  "name": "lolo",
  "password": "alphabet"
  }